### ISSUE TITLE
RSS link not working

### ISSUE THREAD

**Issue by hyde-stevenson** [EdwinWenink/archive_fever#1751]
Hello,

Everything is in the title. I tried to subscribe to your RSS feed, but I got a 404. 

I thought you were on the fediverse, but couldn't find you there. So, here's that GH issue to let you know :)

**Comment by EdwinWenink** [comment]
Thanks for reaching out! A 404 is very strange, there is no authorization on the feed or anything. I just downloaded a random RSS client (FeedDemon) to see if it works and it seems to work for me. Which client are you using for RSS?

Which of the Fediverses do you mean by the way? I have a Mastodon account laying around, but because I don't use it and take >6/12 months to reply to messages there I don't link to it from my webpage anymore. I love the idea of it, but in the end it's still social media and haven't use any social media for several years now.

**Comment by EdwinWenink** [comment]
Validated the feed, I don't see major issues, although there are some interesting recommendations https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.edwinwenink.xyz%2Findex.xml

**Comment by hyde-stevenson** [comment]
Hey,

Now I have access to the file. But, I dont see it in Newsboat, https://github.com/newsboat/newsboat. 

I'll check again to see

**Comment by hyde-stevenson** [comment]
I tried with just your website, and it worked ... weird. 

I'm closing that issue, it's probably on newsboat's side.

**Comment by EdwinWenink** [comment]
Not using my linux box much anymore nowadays, but newsboat is great! I do miss it. Trying with "just my website" makes me curious what you were attempting before. I'd be glad to try and replicate it myself on my Linux box if somehow my RSS is not configured correctly for some applications. Anyways, if it seem to work now: thanks for subscribing and cheers!

**Comment by hyde-stevenson** [comment]
Basically, there is a ~/.newsboat/urls file with all the RSS links. I just put yours in a new file, and it works. 

I switched to the old one, and your feed appeared ... which is weird to be honest. I tried to add log, but I didnt see anything special there :man_shrugging:
